# Generated by Django 5.2.6 on 2025-09-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(to="core.User", related_name="conversations"),
        ),
    ]
