# Generated by Django 5.2.6 on 2025-09-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='msg',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
