# Generated by Django 5.2.6 on 2025-09-11 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_user_username_remove_user_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('password', 'Passwod'), ('google', 'Google'), ('github', 'GitHub')], max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.user')),
            ],
            options={
                'unique_together': {('provider', 'provider_id')},
            },
        ),
    ]
