# Generated by Django 5.2.6 on 2025-09-20 06:27

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(access_key='dummy', addressing_style='path', bucket_name='users-bucket', endpoint_url='http://localhost:9000', region_name='us-east-1', secret_key='dummy'), upload_to=''),
        ),
    ]
